
version: '3.8'

services:
  query-whiz-app:
    build: .
    expose:
      - "5000"
    networks:
      - api-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - query-whiz-app
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
